name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check if S3 bucket exists or create it
        run: |
          if aws s3 ls s3://${{ env.BUCKET_NAME }} 2>&1 | grep -q 'NoSuchBucket'; then
            echo "Bucket does not exist, creating..."
            aws s3 mb s3://${{ env.BUCKET_NAME }}
            
            # Set public bucket policy
            aws s3api put-bucket-policy --bucket ${{ env.BUCKET_NAME }} --policy '{
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": "*",
                  "Action": "s3:GetObject",
                  "Resource": "arn:aws:s3:::${{ env.BUCKET_NAME }}/*"
                }
              ]
            }'
          else
            echo "Bucket exist, proceeding"
          fi

      - name: Deploy to S3 bucket
        run: |
          aws s3 sync ./ s3://${{ env.BUCKET_NAME }} --exclude ".git/*" --exclude ".github/*" --delete
